name: test s3 actions
on:
  workflow_call:
    secrets: # reusable workflows do not have direct access to secrets, we have to pass them from the caller
      ROLE_ARN:
        required: true
    inputs:
      BUCKET_NAME:
        required: true  # if 'required' is 'false', set a default value using default: somevalue
        type: string
      AWS_REGION:
        required: true  # if 'required' is 'false', set a default value using default: somevalue
        type: string
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ROLE_ARN}}
          role-session-name: test-aws-github-hookup
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  Copy index.html to s3 --acl public-read
        run: |
          #  aws s3 mb s3://${{ env.BUCKET_NAME }} --region ${{env.AWS_REGION}}
          sam --version
          aws s3 cp ./resources/index.html s3://${{ env.BUCKET_NAME }}/ --acl public-read
